[wallpapers]
src.git = "https://github.com/kiriashi/wallpapers.git"
fetch.github = "kiriashi/wallpapers"

[Grub-Theme-Arknights_Theresa]
src.git = "https://github.com/Shelton786/Grub-Themes-Arknights_Theresa.git"
fetch.github = "Shelton786/Grub-Themes-Arknights_Theresa"

[monolisa-NF]
src.git = "https://github.com/kiriashi/monolisa-NF.git"
fetch.github = "kiriashi/monolisa-NF"

[monaco-NF]
src.git = "https://github.com/kiriashi/monaco-NF.git"
fetch.github = "kiriashi/monaco-NF"

[wanxiang_base]
src.github_tag = "amzxyz/rime_wanxiang"
src.from_pattern = "^v([0-9]+\\.[0-9]+\\.[0-9]+.*)$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v$ver/rime-wanxiang-base.zip"

[mihomo-party]
src.github_tag = "mihomo-party-org/clash-party"
src.from_pattern = "^v([0-9]+\\.[0-9]+\\.[0-9]+.*)$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/mihomo-party-org/clash-party/releases/download/v$ver/mihomo-party-linux-$ver-amd64.deb"

[tableplus]
src.manual = "LTS"
fetch.url = "https://tableplus.com/release/linux/x64/TablePlus-x64.AppImage"