[wallpapers]
src.git = "https://github.com/kiriashi/wallpaper.git"
fetch.github = "kiriashi/wallpapers"

[wanxiang_base]
src.github = "amzxyz/rime_wanxiang"
src.from_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v$ver/rime-wanxiang-base.zip"

[wanxiang_gram]
src.github = "amzxyz/RIME-LMDG"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram"
