[wallpaper]
src.git = "https://github.com/kiriashi/wallpaper.git"
fetch.github = "kiriashi/wallpaper"

[wanxiang_gram]
src.github = "amzxyz/RIME-LMDG"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram"
