[wallpapers]
src.git = "https://github.com/kiriashi/wallpapers.git"
fetch.github = "kiriashi/wallpapers"

[monolisa-NF]
src.git = "https://github.com/kiriashi/monolisa-NF.git"
fetch.github = "kiriashi/monolisa-NF"

[monaco-NF]
src.git = "https://github.com/kiriashi/monaco-NF.git"
fetch.github = "kiriashi/monaco-NF"

[wanxiang_base]
src.github_tag = "amzxyz/rime_wanxiang"
src.from_pattern = "^v([0-9]+\\.[0-9]+\\.[0-9]+.*)$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v$ver/rime-wanxiang-base.zip"

[wanxiang_gram]
src.github_tag = "amzxyz/RIME-LMDG"
src.from_pattern = "^(LTS)$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram"