[wallpaper]
src.git = "https://github.com/kiriashi/wallpaper.git"
fetch.github = "kiriashi/wallpaper"

[scx]
src.github = "sched-ext/scx"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://codeload.github.com/sched-ext/scx/zip/refs/tags/v$ver"