# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wallpaper = {
    pname = "wallpaper";
    version = "0b36e219d57f4db93ef6b2ad147b5d7422d44470";
    src = fetchFromGitHub {
      owner = "kiriashi";
      repo = "wallpaper";
      rev = "0b36e219d57f4db93ef6b2ad147b5d7422d44470";
      fetchSubmodules = false;
      sha256 = "sha256-vrrnRmV3h5CkU7fCdSQMQw5fU9C4cBX9AWmOu5ieOdQ=";
    };
    date = "2025-09-10";
  };
  wanxiang_base = {
    pname = "wanxiang_base";
    version = "12.6.5";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v12.6.5/rime-wanxiang-base.zip";
      sha256 = "sha256-uZp4/EnLtEX24RvjFGrCihS3GupI2awFypaLfewbYO4=";
    };
  };
  wanxiang_gram = {
    pname = "wanxiang_gram";
    version = "dict-nightly";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-yvAcKdoU9dZ0kPVedNG88+DMSI8KVSMRBGKRVZ7EF1c=";
    };
  };
}
