# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lx-music-desktop = {
    pname = "lx-music-desktop";
    version = "2.11.0";
    src = fetchurl {
      url = "https://github.com/lyswhut/lx-music-desktop/releases/download/v2.11.0/lx-music-desktop_2.11.0_x64.AppImage";
      sha256 = "sha256-CjsTJhT0WXo4SR7Ub8D3+L3xTsItXDcTZUcvmo1t6bU=";
    };
  };
  wallpaper = {
    pname = "wallpaper";
    version = "0b36e219d57f4db93ef6b2ad147b5d7422d44470";
    src = fetchFromGitHub {
      owner = "kiriashi";
      repo = "wallpaper";
      rev = "0b36e219d57f4db93ef6b2ad147b5d7422d44470";
      fetchSubmodules = false;
      sha256 = "sha256-vrrnRmV3h5CkU7fCdSQMQw5fU9C4cBX9AWmOu5ieOdQ=";
    };
    date = "2025-09-10";
  };
}
