# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  monaco-NF = {
    pname = "monaco-NF";
    version = "27dd08bfcadcc84d2df02178d7bf05d413eab0dd";
    src = fetchFromGitHub {
      owner = "kiriashi";
      repo = "monaco-NF";
      rev = "27dd08bfcadcc84d2df02178d7bf05d413eab0dd";
      fetchSubmodules = false;
      sha256 = "sha256-ynzO1my+XeXm9Zex7wxJ9ldRrMNTcuQmDuQtuNHoJa4=";
    };
    date = "2025-09-25";
  };
  monolisa-NF = {
    pname = "monolisa-NF";
    version = "f8aae20e6b2f664f07b9f36bb5af43155de6f087";
    src = fetchFromGitHub {
      owner = "kiriashi";
      repo = "monolisa-NF";
      rev = "f8aae20e6b2f664f07b9f36bb5af43155de6f087";
      fetchSubmodules = false;
      sha256 = "sha256-lwWfVSIwg9pwRzKC2qvHUS/oLIwfLVnI8W7q4nBeIpQ=";
    };
    date = "2025-09-25";
  };
  wallpapers = {
    pname = "wallpapers";
    version = "a1ad4e27ad2b0f037e60b6e429f9d60af0d301cf";
    src = fetchFromGitHub {
      owner = "kiriashi";
      repo = "wallpapers";
      rev = "a1ad4e27ad2b0f037e60b6e429f9d60af0d301cf";
      fetchSubmodules = false;
      sha256 = "sha256-dsOh39ARUh3IaRnG270bgqvj+ausDygKpNNoJeSiAok=";
    };
    date = "2025-09-25";
  };
  wanxiang_base = {
    pname = "wanxiang_base";
    version = "12.6.6";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v12.6.6/rime-wanxiang-base.zip";
      sha256 = "sha256-8clfQAS0X6cs/lYD8XxZx+PwvyjAYQUxKZqB6hDi1A0=";
    };
  };
  wanxiang_gram = {
    pname = "wanxiang_gram";
    version = "v3n2";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256:056eafaa93181e2788a886b0f54cb9dd46a8f3e2fc7bffb5f8e2dcf213edf682";
    };
  };
}
